package main

const tmpl = `// This code was autogenerated from nrpc, do not edit.

package {{ package . }}

import (
	"context"
	"fmt"

	"github.com/LilithGames/nevent"
	"github.com/LilithGames/nrpc"
	"github.com/golang/protobuf/proto"
	"github.com/nats-io/nats.go"
	"google.golang.org/grpc"
)

{{- $foptions := options . }}
{{- $fsubject := default $foptions.Subject (package .) }}
{{- range .Services }}
{{- $svc := .Name }}
{{- $soptions := options . }}
{{- $nrpcoptions := nrpcoptions .}}
{{- $isnrpcsvr := $nrpcoptions.Nrpc }}
{{- $ssubject := default $soptions.Subject $svc }}
{{- $bsubject := printf "%s.%s" $fsubject $ssubject }}
{{- if $isnrpcsvr }}
const (
     {{$svc}}4NRpcName = "NRPC4{{$svc}}"
)

type {{$svc}}NInterface interface {
    {{- range .Methods }}
    {{- $nrpcoptions := nrpcoptions .}}
    {{- $isnrpcfun := $nrpcoptions.Nrpc }}
    {{- if $isnrpcfun }}
	{{ name . }}(ctx context.Context, m *{{ name .Input }}) (*{{ name .Output }}, error)
    {{- end }}
    {{- end }}
}

func Register{{$svc}}NRpc(s *nrpc.Server, in {{$svc}}NInterface, opts ...nevent.ListenOption) error {
    {{- range .Methods }}
    {{- $oname := name .Output }}
    {{- $moptions := options . }}
    {{- $msubject := default $moptions.Subject (name .) }}
    {{- $subject := printf "nrpc.%s.%s.%s" $fsubject $ssubject $msubject }}
    {{- $nrpcoptions := nrpcoptions .}}
    {{- $isnrpcfun := $nrpcoptions.Nrpc }}

    {{- if $isnrpcfun }}
	GenEh{{ name . }} := func(ctx context.Context, m *nats.Msg) (interface{}, error) {
		data := new({{name .Input }})
		err := proto.Unmarshal(m.Data, data)
		if err != nil {
			return nil, fmt.Errorf("nrpc svr {{$subject}} unmarshal ask: %w", err)
		}

        if err := data.Validate(); err != nil {
            return nil, fmt.Errorf("nrpc svr {{$subject}} req validate fail: %w", err)
        }

		resp, err := in.{{ name . }}(ctx, data)
		if err != nil {
			return nil, err
		}

        if err := resp.Validate(); err != nil {
            return nil, fmt.Errorf("nrpc svr {{$subject}} rsp data validate fail: %w", err)
        }

		bs, err := proto.Marshal(resp)
		if err != nil {
			return nil, fmt.Errorf("nrpc svr {{$subject}} marshal answer: %w", err)
		}
		return bs, nil
	}

	{{ name .}}Err := s.RegisterEventHandler("{{$subject}}", GenEh{{ name . }}, opts...)
    if {{name .}}Err != nil {
        return {{name .}}Err
    }
    {{- end}}

    {{- end }}
    return nil
}

// generete for nrpc client
type {{ $svc }}NClientImpl struct {
	nc *nevent.Client
    opt []nevent.EmitOption
}

type {{ $svc }}NRpcClient interface {
{{- range .Methods }}
{{- $moptions := options . }}
{{- $msubject := default $moptions.Subject (name .) }}
{{- $subject := printf "nrpc.%s.%s.%s" $fsubject $ssubject $msubject }}
{{- $nrpcoptions := nrpcoptions .}}
{{- $isnrpcfun := $nrpcoptions.Nrpc }}
{{- if $isnrpcfun }}
    {{ name . }}(ctx context.Context, e *{{ name .Input }}, opts ...grpc.CallOption) (*{{ name .Output }}, error)
{{- end }}
{{- end }}
}

func New{{ $svc }}NRpcClient(nc *nevent.Client, opt ...nevent.EmitOption) {{ $svc }}NRpcClient {
    opList := make([]nevent.EmitOption, 0)
    opList = append(opList, opt ...)
	return &{{ $svc }}NClientImpl{nc: nc, opt: opList} 
}

{{- range .Methods }}
{{- $moptions := options . }}
{{- $msubject := default $moptions.Subject (name .) }}
{{- $subject := printf "nrpc.%s.%s.%s" $fsubject $ssubject $msubject }}
{{- $nrpcoptions := nrpcoptions .}}
{{- $isnrpcfun := $nrpcoptions.Nrpc }}
{{- if $isnrpcfun }}

func (nCli *{{ $svc }}NClientImpl){{ name . }}(ctx context.Context, e *{{ name .Input }}, opts ...grpc.CallOption) (*{{ name .Output }}, error) {
	msg := nats.NewMsg("{{ $subject }}")
    if err := e.Validate(); err != nil {
        return nil, fmt.Errorf("ask event invalidate fail %w", err)
    }
	data, err := proto.Marshal(e)
	if err != nil {
		return nil, fmt.Errorf("ask {{$subject}} marshal error %w", err)
	}
	msg.Data = data
	resp, err := nCli.nc.Ask(ctx, msg, nCli.opt ...)
	if err != nil {
		return nil, fmt.Errorf("ask {{$subject}} %w", err)
	}
	answer := new({{ name .Output }})
	err = proto.Unmarshal(resp, answer)
	if err != nil {
		return nil, fmt.Errorf("answer {{$subject}} unmarshal error %w", err)
	}
    if err := answer.Validate(); err != nil {
        return nil, fmt.Errorf("ask {{$subject}} response validate fail %w", err)
    }

	return answer, nil
}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
`
